### ISSUE TITLE
Tile creation issue

### ISSUE THREAD

**Issue by Muqsit** [korado531m7/InventoryMenuAPI#1]
In `InventoryMenuAPI::sendInventory()`, there's a behaviour which overrides a Tile instance without attempting to recreate or handle the previous Tile instance.

The Tile is created at `$player->y + 4` unless in this case, where the Tile is still created but at `$player->y + 3`:
https://github.com/korado531m7/InventoryMenuAPI/blob/46ed98620882464165ad7461a7729d553a3cf2ff/src/korado531m7/InventoryMenuAPI/InventoryMenuAPI.php#L56

The problem arises when you're overriding a Tile that is already present. For example, if you're overriding a Chest tile already present at those coordinates, you will also be clearing it's inventory.

It looks like you're then following up with spawning a fake tile (block entity) through packets, which is unnecessary because you already created a Tile instance (you could use `Tile->spawnTo($player)`).
https://github.com/korado531m7/InventoryMenuAPI/blob/46ed98620882464165ad7461a7729d553a3cf2ff/src/korado531m7/InventoryMenuAPI/InventoryMenuAPI.php#L129-L135
But anyway, the problem is the creation of Tile instances. That lets other players know about the Tile, which makes it not a completely fake inventory. It doesn't look right when you're sending fake blocks to one player, but fake Tile to every player (lets not talk about those tile instances being saved along with the world).

Looks like the only reason behind creating the tile is so you can obtain an Inventory instance. An alternative would be creating a flexible Inventory instance such as this:
```php
class FlexibleInventory extends ContainerInventory{

    /** @var int */
    protected $network_type;

    public function __construct(int $network_type, Vector3 $holder, array $items = [], int $size = null, string $title = null){
        $this->network_type = $network_type;
        parent::__construct($holder, $items, $size, $title);
    }

    public function getNetworkType() : int{
        return $this->network_type;
    }
}
```

Then you can create the inventory instances this way:
```php
switch($inventoryType){
    case self::INVENTORY_TYPE_CHEST:
        $inv = new FakeInventory(WindowTypes::CONTAINER, new Vector3($x, $y, $z), [], 27);
        break;
    case self::INVENTORY_TYPE_DOUBLE_CHEST:
        $inv = new FakeInventory(WindowTypes::CONTAINER, new Vector3($x, $y, $z), [], 54);
        break;
}
```

This also makes the implementation somewhat lightweight since you no longer need to create a Tile instance only to obtain an Inventory instance. 👍

**Comment by korado531m7** [comment]
sorry for delaying reply.
thank you for sending issue and advising me
i'm embarassed the creation of tile because i thought that inventory can't create without tile
but thank you for your advice, i found it not need to create inventory and sharing the inventory with all players
i'll recreate my plugin using fake inventory if have enough time to edit

i've a question.
it is possible to create other inventory (e.g. Trading Villager inventory) with fake inventory?

**Comment by Muqsit** [comment]
Yes. For trading villager inventory, you only need to spawn the villager — no tile or block. There's a pull request on pmmp that adds villager inventory, I haven't checked it though.

**Comment by korado531m7** [comment]
wow :D

that is to say it's not impletemented on up to date version?
