### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by treehousemc1** [korado531m7/InventoryMenuAPI#11]
I used your InventoryMenuApi sample but got error on clicked item

[02:03:08] [Server thread/DEBUG]: #0 src/pocketmine/plugin/MethodEventExecutor(38): korado531m7\InventoryMenuAPI\EventListener->onReceive(object pocketmine\event\server\DataPacketReceiveEvent)

**Comment by korado531m7** [comment]
thank you for reporting.
please show me more errors.

**Comment by treehousemc1** [comment]
sorry I can't try rn, u can test urself. Also can u add me on discord treehousemc#0691 or twitter @dr3tree

**Comment by korado531m7** [comment]
fixed in 3.0.0,. sample is in 1.1.0

**Comment by treehousemc1** [comment]
Can u add me on discord or twitter? @korado531m7

**Comment by korado531m7** [comment]
sure
i have both

**Comment by treehousemc1** [comment]
OK see u there
