### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by TheOriginDeveloppement** [korado531m7/InventoryMenuAPI#13]
I have an error with a function isReadonly() and getCallable() error call to member function on array please fix that.

**Comment by korado531m7** [comment]
thank tou for reporting.
i'm fixing that, and will be released version 3.0.0 soon :)

**Comment by TheOriginDeveloppement** [comment]
Thank , do you have an idea of the release date of the new version?

**Comment by korado531m7** [comment]
maybe in this week
