### ISSUE TITLE
And again...

### ISSUE THREAD

**Issue by TheWalkingDrift** [korado531m7/InventoryMenuAPI#14]
This Error will be schön in the Console when I try to Chose a Item in with du you Like or Calkulation Test

**Comment by TheWalkingDrift** [comment]
[14:18:18] [Server thread/CRITICAL]: Error: "Call to a member function getTaskId() on null" (EXCEPTION) in "/storage/emulated/0/PocketMine-MP/virions/InventoryMenuAPI-master/src/korado531m7/InventoryMenuAPI/EventListener" at line 34

**Comment by korado531m7** [comment]
thank you for reporting
is it occurred everytime?

**Comment by korado531m7** [comment]
i have fixed it. please confirm yourself :)

**Comment by TheWalkingDrift** [comment]
How can I open the Inventory with a command ?

**Comment by TheWalkingDrift** [comment]
Can you make it for me ?

**Comment by korado531m7** [comment]
create instance and set items to it.
send it to player who entered the command.

**Comment by TheWalkingDrift** [comment]
Should I send you my Plugin ? How is your Discord Name ?

**Comment by korado531m7** [comment]
ok. wait a moment.

**Comment by TheWalkingDrift** [comment]
My Discord Name ist TheWalkingDrift#7924

**Comment by korado531m7** [comment]
sent request
