### ISSUE TITLE
Something went wrong ?

### ISSUE THREAD

**Issue by LamPocketVN** [korado531m7/InventoryMenuAPI#24]
[Server thread/CRITICAL]: TypeError: "Return value of korado531m7\InventoryMenuAPI\InventoryMenu::getPluginBase() must be an instance of pocketmine\plugin\PluginBase, null returned" (EXCEPTION) in "D:/Minecraft Tool/JinodkPrison/virions/InventoryMenuAPI-master/src/korado531m7/InventoryMenuAPI/InventoryMenu" at line 77

**Comment by korado531m7** [comment]
thank you for comment. please show me your code that is registering pluginbase.

**Comment by LamPocketVN** [comment]
I using this plugin as virion :3

**Comment by korado531m7** [comment]
you must activate this api with register function and the parameter must be PluginBase (see documentation)
that is to say, this plugin can't use only putting in the virion folder.
