### ISSUE TITLE
Why player can get item in menu???

### ISSUE THREAD

**Issue by DeadOnBushPH** [korado531m7/InventoryMenuAPI#5]
Help!

**Comment by korado531m7** [comment]
Thank you for reporting.
I just fixed the bug. please use latest release.

**Comment by korado531m7** [comment]
https://github.com/korado531m7/InventoryMenuAPI/releases/tag/v2.2.2-Stable

**Comment by DeadOnBushPH** [comment]
What code I will going to write to prevent player getting item in menu

**Comment by korado531m7** [comment]
can't apply the issue with latest version of plugin?

setReadonly(true) not to allow trading between player and menu inventories
